### ISSUE TITLE
application transport security

### ISSUE THREAD

**Issue by chainone** [soutaro/SMHTTPClient#1]
As far as I know application transport security could be simply disabled in info.plist.
Let me know, if I am wrong. Thanks

**Comment by soutaro** [comment]
Yes, you have an option just disable ATS at all. However, I don't want to do that. I agree with Apple's motivation for ATS.
I developed this library to make a plain text connection to LAN hosts, without opting out ATS.

**Comment by chainone** [comment]
:+1:
